### PR TITLE
Bug 1955749: OCP oauth translations for login pages

### PR DESCRIPTION
**Pull request by sg00dwin**
Related changes 
https://github.com/openshift/oauth-server/pull/71
https://github.com/openshift/oauth-templates/pull/15

Screen Shot 2021-05-06 at 6 13 18 PM
Screen Shot 2021-05-06 at 6 13 32 PM
Screen Shot 2021-05-06 at 6 13 48 PM

cc @jhadvig

### CODE REVIEW

**Comment by jhadvig** [comment]
This PR is linked to https://github.com/openshift/oauth-server/pull/71
@stlaz we are ready for review. PTAL

**Comment by stlaz** [comment]
@sg00dwin What exactly does this do? Your description is lacking any detail.

Also, do not put JIRA ticket IDs into commit messages.

**Comment by sg00dwin** [comment]
> @sg00dwin What exactly does this do? Your description is lacking any detail.

@stlaz 
These updates are part of the effort to translate the OCP branded login, error, and provider html templates
https://github.com/openshift/oauth-templates#red-hat-openshift-container-platform

The OCP branded templates take advantage of the override mechanism by providing customized templates via secrets
This pr updates the Base64-encoded versions of the generated source for `login.html` `errors.html` and `providers.html` https://github.com/openshift/cluster-authentication-operator/blob/master/bindata/oauth-openshift/branding-secret.yaml#L7-L9

**Comment by stlaz** [comment]
needs `make update-bindate` for verification to pass

**Comment by jhadvig** [comment]
The login test is most probably failing due to the fact that the oauth-server changes need to get merged first.

**Pull request merged**
