### PR TITLE
Bug 1740363: operator: improve the reason reporter for route

### PR DESCRIPTION
**Pull request by mfojtik**
There are 50+ degraded auth operators with reason being `RouteStatusDegradedError`. This PR provide more detailed reason string (as don't have access to the message yet). 

/cc @enj 
/cc @stlaz

### CODE REVIEW

**Comment by stlaz** [comment]
/lgtm

I bet there would be a cleaner way to do this, but for now to get better data from support, this is ok.

**Comment by enj** [comment]
/hold

You cannot just change reason - the string is an API.

**Comment by enj** [comment]
> /hold
> 
> You cannot just change reason - the string is an API.

In the sense that the string change can cause issues across upgrades.  You have to manually remove the old value since it's written out to status.  Also this is just a silly workaround to not having proper logs from failing clusters.

**Comment by enj** [comment]
#179

**Pull request closed without merging**
