### PR TITLE
API-1835: bring MOM up to date for testing and the like

### PR DESCRIPTION
**Pull request by deads2k**
Now using the latest library-go and MOM.

### CODE REVIEW

**Comment by deads2k** [comment]
neat thing. This is showing unstable output which is goign to cause repeated writes for the operator.  We never knew before, but now we do.

**Comment by deads2k** [comment]
Oh, and we didn't cause the unstable writes. It's simply made it obvious to us.

**Comment by p0lyn0mial** [comment]
/lgtm

/hold

so that @ibihim and @liouk have a chance to review it :)

**Comment by deads2k** [comment]
time's up

/hold cancel

**Pull request merged**
