### PR TITLE
oauth-server: deployment precondition - wait for config present instead of route admited

### PR DESCRIPTION
**Pull request by stlaz**
We don't need a successfully admitted route in order for the oauht-server to properly deploy.

/assign @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

This matches the actual requirement of the oauth-server deployment.

**Comment by stlaz** [comment]
/hold
too many re-runs, time to investigate

**Comment by stlaz** [comment]
Looks like an issue with the cluster ingress, this was forwarded to the network-edge team for investigation. https://bugzilla.redhat.com/show_bug.cgi?id=1929396 might be the cause.

**Comment by stlaz** [comment]
/hold cancel
/retest

the issue might be fixed by https://github.com/openshift/origin/pull/26808, let's see

**Comment by stlaz** [comment]
/retest
looks like azure upgrade jobs success rate imrpoved by 20% recently, let's see

**Comment by stlaz** [comment]
/retest
i/o timeouts during installation

**Comment by stlaz** [comment]
/hold cancel
/retest
there were some other CI fixes, let's see

**Comment by stlaz** [comment]
/hold
for the above fix

**Pull request closed without merging**
