### PR TITLE
Bug 1729289:  Fix bug where favicon is incorrect (was Shadowman, now OpenShift)

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1729289

@spadgett, @enj not sure how to test locally.  The favicon for OKD/OSE is correct as is (is the OKD icon.

### CODE REVIEW

**Comment by enj** [comment]
/cherrypick release-4.1

I will test locally and tag if it works.

**Comment by stlaz** [comment]
/lgtm
Appears to work on my cluster

**Pull request merged**
