### PR TITLE
Delete operator 1

### PR DESCRIPTION
**Pull request by enj**
Delete operator 1

This is the minimal change to remove operator 1.  It does not attempt to update operator 2 to remove the "2" or make other cosmetic changes.

Signed-off-by: Monis Khan <mkhan@redhat.com>

---

Set operator 2 to Managed

Since operator 1 is gone, operator 2 needs to run by default to allow kube:admin to work.

Signed-off-by: Monis Khan <mkhan@redhat.com>

---

/hold

We need the router fixes for this to work.  The `kube:admin` test should fail and prevent this from merging until then.

### CODE REVIEW

**Comment by enj** [comment]
```
fail [github.com/openshift/origin/test/extended/bootstrap_user/bootstrap_user_login.go:52]: Expected error:
    <*util.ExitError | 0xc42293ec60>: {
        Cmd: "oc login --config=/tmp/configfile618696739 --namespace=e2e-test-bootstrap-login-vs8pt -u kubeadmin -p qs83sHr1AzvftWmAw1vWR5yaJX5z9BXWAPoXjMhvfaw",
        StdErr: "error: x509: certificate signed by unknown authority",
        ExitError: {
            ProcessState: {
                pid: 15025,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 226357},
                    Stime: {Sec: 0, Usec: 59447},
                    Maxrss: 95120,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 15167,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 0,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 1094,
                    Nivcsw: 1,
                },
            },
            Stderr: nil,
        },
    }
    exit status 1
not to have occurred
```

@sallyom look!  A test that catches regressions!  It is annoying that the password gets logged though :expressionless:

**Comment by stlaz** [comment]
/hold cancel
The routes were fixed.

**Comment by stlaz** [comment]
Currently blocked by https://github.com/openshift/installer/pull/1242

**Comment by abhinavdahiya** [comment]
> Currently blocked by [openshift/installer#1242](https://github.com/openshift/installer/pull/1242)
[openshift/installer#1242](https://github.com/openshift/installer/pull/1242) [merged](https://github.com/openshift/installer/pull/1242#event-2143090947)

**Comment by abhinavdahiya** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-authentication-operator/59/pull-ci-openshift-cluster-authentication-operator-master-e2e-aws/260/
seems stuck in running with no progress...

/test e2e-aws

**Pull request merged**
