### PR TITLE
Bug 1828457: bump(*): vendor update

### PR DESCRIPTION
**Pull request by mfojtik**
* openshift/api@27f2726: Add Route for consoles custom hostname
* openshift/api@1f59593: Add VirtualHostedStyle to S3 configuration options
* openshift/api@366fdb3: Adds WildcardPolicy field to IngressController API
* openshift/api@d363d3f: Update optional tags where needed
* openshift/api@710ab01: Fix the default for Authentication.ServiceAccountIssuer
* openshift/api@556c4b9: make update
* openshift/api@27622da: Replace library-go references with build-machinery-go for CRD gen readme
* openshift/api@722c7a6: enable priority and fairness for kube-apiserver
* openshift/api@f5df921: Builds: Make a bunch of fields omitempty
* openshift/api@6c25f0f: config/v1/types_infrastructure.go: add service endpoints to aws platform spec and status
* openshift/api@1fc310b: operator/ingress: Add logging API
* openshift/api@2dadc74: config/v1/types_infrastructure.go: update the cloudConfig spec to define the generated one's location
* openshift/api@b7121e1: config/v1: add status subresource for infrstrastructure
* openshift/api@0f7ea19: bump to kube v1.18.2
* openshift/api@9e7957d: bump(build-machinery-go)
* openshift/build-machinery-go@8c085b9: Switch to go-bindata/go-bindata for consistency with upstream
* openshift/library-go@ddf4747: add WithCustomInstaller method to Builder interface
* openshift/library-go@4c47103: Fix SA token sync
* openshift/library-go@a39bf28: fileObserver: detect file existence when adding reactor
* openshift/library-go@b833546: Fix serving-certs race for controller's NewCommand*
* openshift/library-go@609e151: Fix ApplySecret for type changes
* openshift/library-go@e43e3d5: Fix error handling of status controller
* openshift/library-go@114736d: cmdbuilder: add WithVersion() that reports version metrics of binary
* openshift/library-go@eca6660: cmd: add WithVersion to StartController
* openshift/library-go@a20f1d9: Fix Apply{Deployment,Deployment} to copy input before mutatating
* openshift/library-go@42af545: Update ApplyDeployment to rely on a hash of the spec
* openshift/library-go@3b4f06f: Update ApplyDaemonSet to rely on a hash of the spec
* openshift/library-go@82e3f52: Bug 1826259: fix ingress CA cert location
* openshift/library-go@c1de486: Remove bitbucket.org/ww/goautoneg dependency
* openshift/library-go@4960ca0: Bump to kube v1.18.2
* openshift/library-go@d14c889: version: make sure to always have namespace when reporting version
* openshift/library-go@556325f: resourcesynccontroller: fix race in unit test
* openshift/library-go@b3ec7d2: vendor: Consolidate onto github.com/munnerz/goautoneg
* openshift/library-go@7813cff: staticpodstate: improve condition and event messages
* openshift/library-go@efe996a: bump(api,build-machinery-go)
* openshift/library-go@029d40b: Switch go go-bindata/go-bindata for consistency with upstream
* openshift/library-go@53b922b: make update
* openshift/library-go@e07b183: Update featuregate unit test to include APIPriorityAndFairness=true
* openshift/library-go@209722f: events: wire graceful broadcaster shutdown

### CODE REVIEW

**Comment by mfojtik** [comment]
@marun @stlaz can you review the react changes?

**Comment by stlaz** [comment]
note that the deployment change was already done in https://github.com/openshift/cluster-authentication-operator/pull/272 but did not have a valid BZ attached, similarly to this PR...

**Comment by stlaz** [comment]
/lgtm cancel
I was not paying enough attention to the changes, please rebase on top of the mentioned PR

**Pull request merged**
