### PR TITLE
Bug 1874056: inline apiserver-lib-go ToFlagSlice to prevent k/k dep

### PR DESCRIPTION
**Pull request by stlaz**

### CODE REVIEW

**Comment by stlaz** [comment]
looks like something broke in golang 1.15 and I'm missing some files so that I can `go mod` properly :thinking:

**Comment by stlaz** [comment]
/hold cancel
the failure was caused by a partial modcache clean yesterday, full cache clean fixed the weird issue

**Review by soltysh — APPROVED** [review]
/lgtm
/retest

**Pull request merged**
