### PR TITLE
OCPBUGS-33654: update OpenShift favicon to new brand standard

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://github.com/openshift/cluster-authentication-operator/pull/670 that incorrectly changed the product name to OpenShift Container Platform.

After:
Screenshot 2024-05-28 at 8 27 11 AM
Screenshot 2024-05-28 at 8 27 23 AM

### CODE REVIEW

**Comment by rhamilto** [comment]
@stlaz, mind approving?

**Comment by stlaz** [comment]
how's this different from https://github.com/openshift/cluster-authentication-operator/pull/670 ?

**Comment by rhamilto** [comment]
> how's this different from #670 ?

It changes the logo back to the correct one (Red Hat OpenShift) as I erroneously changed it to Red Hat OpenShift Container Platform in #670.

**Pull request merged**
