### PR TITLE
[4.7] Bug 1941840: endpoints controller: close response bodies

### PR DESCRIPTION
**Pull request by stlaz**

### CODE REVIEW

**Comment by stlaz** [comment]
Turns out that the memory consumption is triggered on proxy configuration. While the network checkers not closing the bodies was bad, the proxy checker actually uses custom CAs, and when such client hangs out idly on the heap, so do the certificate bundles. And that can eat a lot of memory.

heap

**Comment by rhpmali** [comment]
Added comment in the https://bugzilla.redhat.com/show_bug.cgi?id=1941840#c25 , Still observing memory increase.

**Comment by stlaz** [comment]
There was a missing commit that I failed to push to this backport :|

**Comment by rhpmali** [comment]
Added comment in BZ : https://bugzilla.redhat.com/show_bug.cgi?id=1941840#c27 

/lgtm

**Pull request merged**
