### PR TITLE
Update login templates to PatternFly 4 design

### PR DESCRIPTION
**Pull request by rhamilto**
The raw templates can be viewed at:

* https://rhamilto.github.io/oauth-templates/ocp/errors.html
* https://rhamilto.github.io/oauth-templates/ocp/login.html
* https://rhamilto.github.io/oauth-templates/ocp/providers.html

How to test:
1.  Scale `cluster-version-operator` to zero pods by visiting `k8s/ns/openshift-cluster-version/deployments/cluster-version-operator` and using the pod donut controls to set pods to zero.  Additionally, pause rollouts via `Actions > Pause Rollouts`.
1.  Delete the existing branding secret via `oc delete secret v4-0-config-system-ocp-branding-template -n openshift-authentication`
1.  Recreate the branding secret via `oc create -f https://raw.githubusercontent.com/openshift/cluster-authentication-operator/<HASH>/manifests/06_branding_secret.yaml`
1.  Delete existing openshift-authentication pods so they are regenerated with the new branding secret via `oc delete pods --all -n openshift-authentication`

oauth-openshift apps rhamilto devcluster openshift com_oauth_authorize_client_id=console-oauth-client redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauth%2Fcallback response_type=code scope=user%3Afull state=fadafc79
oauth-openshift apps rhamilto devcluster openshift com_login_test_then=%2Foauth%2Fauthorize%3Fclient_id%3Dconsole-oauth-client%26idp%3Dtest%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A9000%252Fauth%252Fcallback%26response_type%3Dcode%
oauth-openshift apps rhamilto devcluster openshift com_login_test_reason=user_required then=%2Foauth%2Fauthorize%3Fclient_id%3Dconsole-oauth-client%26idp%3Dtest%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A9000%252Fauth%252Fcallback%26
oauth-openshift apps rhamilto devcluster openshift com_login_test_reason=access_denied then=%2Foauth%2Fauthorize%3Fclient_id%3Dconsole-oauth-client%26idp%3Dtest%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A9000%252Fauth%252Fcallback%26

cc: @spadgett, @benjaminapetersen

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
@rhamilto I think you can take that file & `oc apply -f <secret-file>` and it should replace whats deployed.  If I run:

```
oc get secret -n openshift-authentication
NAME                                       TYPE                                  DATA   AGE
builder-dockercfg-rmgb2                    kubernetes.io/dockercfg               1      4d20h
builder-token-gnwst                        kubernetes.io/service-account-token   4      4d20h
builder-token-z7h8z                        kubernetes.io/service-account-token   4      4d20h
default-dockercfg-29j8n                    kubernetes.io/dockercfg               1      4d20h
default-token-5sn44                        kubernetes.io/service-account-token   4      4d20h
default-token-d59zb                        kubernetes.io/service-account-token   4      4d21h
deployer-dockercfg-zfzrt                   kubernetes.io/dockercfg               1      4d20h
deployer-token-s4jw8                       kubernetes.io/service-account-token   4      4d20h
deployer-token-vc6tc                       kubernetes.io/service-account-token   4      4d20h
oauth-openshift-dockercfg-zdpjj            kubernetes.io/dockercfg               1      4d20h
oauth-openshift-token-598h8                kubernetes.io/service-account-token   4      4d21h
oauth-openshift-token-9hjl8                kubernetes.io/service-account-token   4      4d20h
# here is your name: v4-0-config-system-ocp-branding-template
v4-0-config-system-ocp-branding-template   Opaque                                3      4d21h
v4-0-config-system-router-certs            Opaque                                1      4d20h
v4-0-config-system-serving-cert            kubernetes.io/tls                     2      4d20h
v4-0-config-system-session                 Opaque                                1      4d20h
```

**Comment by stlaz** [comment]
@benjaminapetersen is the console-login test failing because of the new template?

**Comment by stlaz** [comment]
Small correction to the testing comment:
Step 0: disable CVO managing the secret so that you don't have to try to compete with it.

I couldn't get a cluster up yet since we seem to be hitting AWS limits against, I'll try that afterwards, including the oauth-server.

The IdM selection is a must-have though, if it's not there yet, add it, please.

**Comment by rhamilto** [comment]
> @benjaminapetersen is the console-login test failing because of the new template?

Indeed it is.  Tests are looking for the old PF3 login class (`.login-pf`) that has been changed to the new PF4 login class (`.pf-c-login`).  Lemme update the tests in a way that will work with both the old and new login templates.

**Comment by rhamilto** [comment]
`ci/prow/e2e-aws-console-login` should pass once https://github.com/openshift/console/pull/4029 merges.

**Comment by stlaz** [comment]
tested in my cluster with 2 IdPs, selecting an IdP worked so I think we can merge this once the tests pass.

**Comment by spadgett** [comment]
I've confirmed the `stable:console-tests` image used in the last run didn't have the test changes from openshift/console#4029, which is why `e2e-aws-console-login` failed

**Comment by stlaz** [comment]
/lgtm
installation seems to be in quite a bad shape lately, let's have /retests automatically

**Pull request merged**
