### PR TITLE
[release-4.1] Bug 1725936: Split handling of degraded across multiple conditions

### PR DESCRIPTION
**Pull request by enj**
Supersedes #145

/assign @stlaz

### CODE REVIEW

**Comment by jwforres** [comment]
Given the large number of bumps in this PR I'd like to see an ack from @sttts or @mfojtik

**Comment by mfojtik** [comment]
/lgtm

@jwforres this is supporting our effort to provide more context for the degraded conditions for this operator that we see in the graphana dashboard.

**Comment by jwforres** [comment]
Thanks, just wanted more eyes since the bumps were new in this PR compared to the one it replaced. Will approve.

**Pull request merged**
