### PR TITLE
Bug 1982726: encryption-controller: sync secrets conditionally

### PR DESCRIPTION
**Pull request by dgrisonnet**
Update the version of library-go to include the latest changes that
allow the encryption controller to synchronize the encryption-config
secret only when the encryption controller should be run. This prevents
the secrets from being unnecessarily deleted in the apiserver namespace
whenever it doesn't exist in the config-managed namespace.

Follow-up to openshift/library-go#1243

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/assing @stlaz 

for approval

**Comment by p0lyn0mial** [comment]
we have similar PRs for kas-o (https://github.com/openshift/cluster-kube-apiserver-operator/pull/1255) and oas-o

**Comment by s-urbaniak** [comment]
e2e failures seem unrelated

**Pull request merged**
