### PR TITLE
Restore run level 9

### PR DESCRIPTION
**Pull request by enj**
Signed-off-by: Monis Khan <mkhan@redhat.com>

@openshift/sig-auth I expect this to fail CI and I expect #43 to pass CI now that I have rebased it on master.  Lets see what happens.

### CODE REVIEW

**Comment by stlaz** [comment]
The tests passing should be a good enough sign for this to get merged.
/lgtm

**Comment by enj** [comment]
/hold

I do not think there is need for the bot to keep rerunning this.  Run level seems to be linked to the CI failures we are seeing.

I will manually rerun it once to show that the failure is consistent:

/retest

**Comment by enj** [comment]
And #43 passed without issue!

**Comment by stlaz** [comment]
Let me steal this PR for a bit to experiment with what's actually breaking CI. Chipping away deployments.

**Comment by stlaz** [comment]
So it fails even with deployments delayed.

**Pull request closed without merging**
