### PR TITLE
pick kube 1.17.1

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
could you also update `github.com/openshift/client-go`, github.com/openshift/library-go and github.com/openshift/api` ? (for example https://github.com/openshift/openshift-apiserver/pull/68/commits/14b2dc4c3e1d0bee1930bb16037ab8ede77763ba)

**Comment by tkashem** [comment]
> could you also update `github.com/openshift/client-go`, github.com/openshift/library-go and github.com/openshift/api` ? (for example [openshift/openshift-apiserver@14b2dc4](https://github.com/openshift/openshift-apiserver/commit/14b2dc4c3e1d0bee1930bb16037ab8ede77763ba))

@p0lyn0mial I updated the openshift dependencies to
```
	github.com/openshift/api v0.0.0-20200116145750-0e2ff1e215dd
	github.com/openshift/client-go v0.0.0-20200116152001-92a2713fa240
	github.com/openshift/library-go v0.0.0-20200120084036-bb27e57e2f2b
```

**Comment by stlaz** [comment]
/lgtm cancel
vendor does not match

**Comment by tkashem** [comment]
> /lgtm cancel
> vendor does not match

@stlaz, before I made any change, I ran `go mod vendor` and `go mod tidy` to make sure the vendor folder is clean. But I noticed that some packages were not vendored in. Let me double check, thanks for checking it!

**Pull request merged**
