### PR TITLE
bug 1893386: update ingress node available to handle custom placement

### PR DESCRIPTION
**Pull request by deads2k**
/hold for unit tests

This adds code to honor the node placement on the ingress controller https://github.com/openshift/cluster-ingress-operator/blob/c6491b2c5d04f81aa36b3c409de1c49a5c228ae3/pkg/operator/controller/ingress/deployment.go#L342-L347

/assign @mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
/lgtm

retag after unit test exists

/cherrypick release-4.6

**Comment by deads2k** [comment]
/hold cancel

now with unit tests

**Comment by deads2k** [comment]
retagging per michal's comment.

**Pull request merged**
