### PR TITLE
Fix upstream regression [1] where login box can be narrower than view…

### PR DESCRIPTION
**Pull request by rhamilto**
…port at mobile

[1] https://github.com/patternfly/patternfly/issues/2913

After:
oauth-openshift apps rhamilto devcluster openshift com_oauth_authorize_client_id=console redirect_uri=https%3A%2F%2Fconsole-openshift-console apps rhamilto devcluster openshift com%2Fauth%2Fcallback response_type=code scope=user%3Afull stat
oauth-openshift apps rhamilto devcluster openshift com_login_kube_admin_then=%2Foauth%2Fauthorize%3Fclient_id%3Dconsole%26idp%3Dkube%253Aadmin%26redirect_uri%3Dhttps%253A%252F%252Fconsole-openshift-console apps rhamilto devcluster openshift
Screen Shot 2020-04-01 at 5 53 22 PM
Screen Shot 2020-04-01 at 5 53 38 PM

### CODE REVIEW

**Comment by rhamilto** [comment]
/hold cancel

@stlaz, PTAL.

**Comment by rhamilto** [comment]
/hold

the bug fix introduced a new bug.  :/

**Comment by rhamilto** [comment]
/hold cancel

fixed the bug.  ready for review.

**Comment by stlaz** [comment]
@rhamilto does this need any backporting?

**Comment by rhamilto** [comment]
> @rhamilto does this need any backporting?

No as the changes are specific to 4.5.

**Comment by rhamilto** [comment]
> @rhamilto does this need any backporting?

@stlaz, given the delay of 4.4,  @spadgett, @benjaminapetersen, and I think we should aim to get the new logos in to 4.4.  so this is going to require a back port.

/cherry-pick release-4.4

**Comment by rhamilto** [comment]
Manually created back port PR for 4.4:  https://github.com/openshift/cluster-authentication-operator/pull/267

**Pull request merged**
