### PR TITLE
[release-4.16] OCPBUGS-34790: update OpenShift favicon to new brand standard

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
@stlaz, mind adding `approved` and `backport-risk-assessed` labels?

**Comment by liouk** [comment]
We need the following fixes in 4.16 for the 4.16 tests to pass:
- https://github.com/openshift/cluster-authentication-operator/pull/681
- https://github.com/openshift/cluster-authentication-operator/pull/682

**Pull request merged**
