### PR TITLE
adds a stub for TestPerfEncryptionTypeAESCBC

### PR DESCRIPTION
**Pull request by p0lyn0mial**
the test will be moved from oaso - https://github.com/openshift/cluster-openshift-apiserver-operator/blob/master/test/e2e-encryption-perf/encryption_perf_test.go

### CODE REVIEW

**Comment by stlaz** [comment]
/retest
looks like the IAM error from yesterday

**Comment by stlaz** [comment]
/retest
...

**Comment by p0lyn0mial** [comment]
e2e-agnostic will be unblocked by openshift/origin#25732

**Comment by p0lyn0mial** [comment]
/close

https://github.com/openshift/cluster-authentication-operator/pull/379 will merge first.

**Pull request closed without merging**
