### PR TITLE
MGMT-9797 - Bump `openshift/api` dependency to `04e1813ebb11`

### PR DESCRIPTION
**Pull request by omertuc**
```bash
go get github.com/openshift/api@04e1813ebb1111ff50756573dbdc17f81aaddb7b
go mod vendor
go mod tidy
```

The openshift/api@04e1813 commit
introduced a new field in the Ingress config CR's status. Since the
cluster-authentication-operator [modifies](https://github.com/openshift/cluster-authentication-operator/blob/7effa5c57bbbce1aea6c19d49ab5b24167c662d1/pkg/controllers/customroute/custom_route_controller.go#L301) this resource,
it has to be aware of its new structure, otherwise it would overwrite the
newly added parameter it is not aware of to its default value, which
is unwanted.

In order to make the cluster-authentication-operator aware of the new
parameter, bumping its `openshift/api` dependency to https://github.com/openshift/api/commit/04e1813ebb1111ff50756573dbdc17f81aaddb7b
and vendoring the changes is required, and this is all that this commit
is doing.

### CODE REVIEW

**Comment by stlaz** [comment]
@omertuc being a Red Hatter, you should know that this is not how open source is done.

Please provide information about what you are trying to do in the PR description for the maintainers of this repository, this currently looks more like spam as it is not making much sense.

**Comment by omertuc** [comment]
Sorry about this, I thought the WIP in the title communicates that this is not something I expect anyone to review. Of course that once this is ready all the necessary details will be included.

As a consequence of the new no-feature-freeze process, my only way to have my https://github.com/openshift/api PR merged is first creating PRs in all repos that need to consume it, and then have cluster-bot build a release out of them so QE can test it

**Comment by stlaz** [comment]
> Sorry about this, I thought the WIP in the title communicates that this is not something I expect anyone to review. Of course that once this is ready all the necessary details will be included.

Putting a "WIP" in a PR name does not nullify your responsibility to notify maintainers of a repository about what you are doing.

> As a consequence of the new no-feature-freeze process, my only way to have my https://github.com/openshift/api PR merged is first creating PRs in all repos that need to consume it, and then have cluster-bot build a release out of them so QE can test it, so I'm creating a lot WIP PRs all over the openshift organization.

I have no idea what your API change is but switching the o/API vendor in most repositories does not have any effect and so you're very likely doing that in vain.

**Comment by omertuc** [comment]
/test e2e-console-login 

looks like unrelated ipi installation flake

**Pull request merged**
