### PR TITLE
Bug 1740121: Prevent global sync error degraded status flapping

### PR DESCRIPTION
**Pull request by enj**
Signed-off-by: Monis Khan <mkhan@redhat.com>

### CODE REVIEW

**Comment by enj** [comment]
I have confirmed that this stops the degraded status flapping by purposefully breaking service-ca.  The CO resource correctly went degraded and the `authentication.operator` resource went degraded once and stayed that way until service-ca was fixed (at which point it returned to normal).

**Comment by sallyom** [comment]
/lgtm

took me a few minutes to follow what was happening in this PR : ), got it now

**Pull request merged**
