### PR TITLE
update for library-go

### PR DESCRIPTION
**Pull request by EmilyM1**
Updates cluster-authentication-operator to reflect oauth token deletion from this library-go PR 
https://github.com/openshift/library-go/pull/1007

### CODE REVIEW

**Comment by stlaz** [comment]
/hold

The referenced lib-go revision does not contain the patch (and therefore there were no actual changes to the contents of the vendor/ directory)

**Comment by stlaz** [comment]
/close
changes merged as a part of #414

**Comment by EmilyM1** [comment]
Changes to bindata are merged with https://github.com/openshift/cluster-authentication-operator/pull/414

**Pull request closed without merging**
