### PR TITLE
Remove top level config CRDs

### PR DESCRIPTION
**Pull request by enj**
These have moved to cluster-config-operator.

Signed-off-by: Monis Khan <mkhan@redhat.com>

@deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm
/hold

you'll want to wait for the cluster-config-operator changes

**Comment by stlaz** [comment]
Blocked by:
https://github.com/openshift/cluster-config-operator/pull/9
https://github.com/openshift/cluster-config-operator/pull/10

**Pull request merged**
