### PR TITLE
Bug 1883792: move to klog/v2 and bump kube/openshift deps

### PR DESCRIPTION
**Pull request by stlaz**

### CODE REVIEW

**Comment by stlaz** [comment]
I guess the loglevel bumps from https://github.com/openshift/cluster-authentication-operator/pull/353 are required, let's wait for that to merge

**Comment by stlaz** [comment]
-retest

**Comment by stlaz** [comment]
/retest
let's just try this

**Comment by mfojtik** [comment]
/hold

the CI failure seems real

**Pull request merged**
