### PR TITLE
Migrate from hypershift to oauth-server image

### PR DESCRIPTION
**Pull request by sallyom**
/cc @deads2k @tnozicka 

Depends on:
https://github.com/openshift/release/pull/4215
https://github.com/openshift/origin/pull/23283

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
(explicitly for those deps)

**Comment by enj** [comment]
Hell yes 🎉

/lgtm

**Comment by stlaz** [comment]
/hold cancel
Deps merged.
/retest

**Pull request merged**
