### PR TITLE
Bug 1996647: endpointsaccessible: clarify degraded message when DNS is broken

### PR DESCRIPTION
**Pull request by mfojtik**
This turns message like:

`Operator unavailable (OAuthServerRouteEndpointAccessibleController_EndpointUnavailable): OAuthServerRouteEndpointAccessibleControllerAvailable: Get "https://oauth-openshift.apps.ci-op-6izkt7mz-16f7c.gcp-2.ci.openshift.org/healthz": dial tcp: lookup oauth-openshift.apps.ci-op-6izkt7mz-16f7c.gcp-2.ci.openshift.org on 172.30.0.10:53: no such host`

to:

`Operator unavailable (OAuthServerRouteEndpointAccessibleController_EndpointUnavailable): OAuthServerRouteEndpointAccessibleControllerAvailable: Get "https://oauth-openshift.apps.ci-op-6izkt7mz-16f7c.gcp-2.ci.openshift.org/healthz": dial tcp: lookup oauth-openshift.apps.ci-op-6izkt7mz-16f7c.gcp-2.ci.openshift.org on 172.30.0.10:53: no such host (this is likely result of malfunctioning DNS server)`

### CODE REVIEW

**Comment by s-urbaniak** [comment]
/lgtm
thank you! :tada:

**Comment by stlaz** [comment]
/bugzilla refresh
/retest
not sure I understand what's going on in this PR but the CI appears a bit stuck

**Comment by stlaz** [comment]
/retest
/trickortreat
is the CI stuck here?

**Pull request merged**
