### PR TITLE
bug 2042038: bump library go

### PR DESCRIPTION
**Pull request by EmilyM1**
Library go bump to delete managed fields

### CODE REVIEW

**Comment by stlaz** [comment]
What's the related lib-go change?

**Comment by tkashem** [comment]
> What's the related lib-go change?

two changes:
- leader election changes we are rolling out across all operators
- and the new audit API change for managed fields.

**Comment by tkashem** [comment]
LGTM

will let others a chance to review

**Comment by tkashem** [comment]
@Emily_Moss you can use either of these two BZs for your PR to have a valid bug label:
- https://bugzilla.redhat.com/show_bug.cgi?id=2041541
- https://bugzilla.redhat.com/show_bug.cgi?id=2041554

**Pull request merged**
