### PR TITLE
Annotate manifests for single-node-developer cluster profile

### PR DESCRIPTION
**Pull request by guillaumerose**
This implements phase 1 of openshift/enhancements#482

### CODE REVIEW

**Comment by rkukura** [comment]
Do the manifests under vendor/github.com/openshift/api also need to be updated to pickup the profile annotations?

**Comment by stlaz** [comment]
Please explain in details of what the annotation actually does in the commit message, link to an enhancement won't do for anyone who wants to quickly understand why the annotation's there.

I haven't read the enhancement and I do not know the consequences of this annotation. Single-node cluster sounds contradictive. Does that mean the operator's code will need to change? Who is going to implement the necessary changes?

**Comment by guillaumerose** [comment]
I updated the commit message.

In a future release, cluster profile will be used to determine which manifests will be applied by the CVO. The default profile is `self-managed-high-availability`. 
CRC will use a new one, `single-node-developer` and edge production cluster  `single-node-production`.

> Does that mean the operator's code will need to change?

Yes. Right now, we don't modify operators but in the future we might have to open PRs to fine tune operators for our profile. 
For this operator, a good thing for us would be to customize https://github.com/openshift/cluster-authentication-operator/blob/master/manifests/02_config.cr.yaml and directly include `useUnsupportedUnsafeNonHANonProductionUnstableOAuthServer`. 

> Who is going to implement the necessary changes?

Teams that need it. For the single-node-developer profile, CRC team.

**Comment by stlaz** [comment]
/hold cancel

> > Who is going to implement the necessary changes?

> Teams that need it. For the single-node-developer profile, CRC team.

I'm taking your word for it, then ;)

**Comment by cfergeau** [comment]
I don't think the CI failures are related to this PR? Are there ongoing issues with CI?

**Pull request merged**
