### PR TITLE
Add base to wiring-in the oauth-apiserver

### PR DESCRIPTION
**Pull request by stlaz**
cc @deads2k

### CODE REVIEW

**Comment by stlaz** [comment]
/hold
There's a couple other controllers that will have to be wired in to get the apiserver in I see, let's get this base done right

**Comment by marun** [comment]
@stlaz Any pointers as to what motivates this change?

**Comment by stlaz** [comment]
/close

Thanks for pointing me to this PR, I forgot to close it.

This was supposed to be what's https://github.com/openshift/cluster-authentication-operator/pull/243 is now

**Pull request closed without merging**
